osx_image: xcode9.3
language: objective-c
xcode_workspace: Iterable-iOS-SDK.xcworkspace
xcode_scheme: Iterable-iOS-SDKTests
xcode_sdk: iphonesimulator

before_install:
  - gem install xcpretty xcpretty-travis-formatter

script:
  - xcodebuild test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' -workspace Iterable-iOS-SDK.xcworkspace -scheme IterableAppExtensionsTests CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -f `xcpretty-travis-formatter`
  - xcodebuild test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' -workspace Iterable-iOS-SDK.xcworkspace -scheme Iterable-iOS-SDKTests CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -f `xcpretty-travis-formatter`
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)